### ISSUE TITLE
pygitrepo-init fails

### ISSUE THREAD

**Issue by noamzilo** [MacHu-GWU/pygitrepo-project#1]
following the readme, i did
pip install pygitrepo
and it worked.

then
C:\WINDOWS\system32>pygitrepo-init gym-thread-art
'pygitrepo-init' is not recognized as an internal or external command,
operable program or batch file.

**Comment by MacHu-GWU** [comment]
It is because of your ``C:\Python27\Scripts`` are not added to system environment variable. Follow this guide https://java.com/en/download/help/path.xml, add your Scripts folder to ``PATH`` variable.

Please leave me message if it doesn't work for you.
