### ISSUE TITLE
安装完没有pygitrepo-init命令

### ISSUE THREAD

**Issue by lndyzwdxhs** [MacHu-GWU/pygitrepo-project#2]
rt

**Comment by MacHu-GWU** [comment]
你肯定是因为你在 virtualenv 环境中安装了, 但是你用全局的 pygitrepo-ini 命令, 所以找不到. 我建议安装到全局的 pip 中, 而不是 virtualenv 中.

另外, 这个项目已经不再维护了, 而是迁徙到了另一个项目中: https://github.com/MacHu-GWU/cookiecutter-pygitrepo

命令和 pygitrepo 类似, 不过更加多彩色高亮的提示, 以及更简化的命令. 你可以看看

**Comment by MacHu-GWU** [comment]
@LoveXiaoLiu  请告诉我是否解决了您的问题. 谢谢.

**Comment by lndyzwdxhs** [comment]
@MacHu-GWU 在全局Python环境中安装了，还是不行，如下图：

![image](https://user-images.githubusercontent.com/16411017/60563687-73c9cd00-9d8f-11e9-9934-963d71382b30.png)

**Comment by MacHu-GWU** [comment]
@LoveXiaoLiu  不好意思, 0.0.27 版本中我不小心把 command line integration 给覆盖掉了, 导致没有激活命令行模式, 我很快的 hotfix 了, release 了 0.0.28 版本, 经过测试已经可以了. ``pip install --upgrade pygitrepo`` 一下即可.

另外的是, 这个库不会添加新的 feature 了, 该项目迁徙到了 https://github.com/MacHu-GWU/cookiecutter-pygitrepo, 项目模板的生成采用了 python 业内使用的 cookiecutter. 添加了高亮彩色的 make 命令的, 修复了一些 bug, 并且会持续的维护. 将来会添加 pipenv 的集成. 还请关注~

谢谢

**Comment by lndyzwdxhs** [comment]
我调用了initiate_project.py模块的initiate_project创建成功了。

感谢积极的fixbug，我会关注你的新项目。

**Comment by lndyzwdxhs** [comment]
@MacHu-GWU 麻烦问一下，有没有开源交流群麻烦加一下我，刚开始接触开源。

**Comment by MacHu-GWU** [comment]
@LoveXiaoLiu  没有哦, 我也是一步步的做开源, 做了 8 年多慢慢积累的. 我目前有 30 多个库在 Pip install 上. 因为我需要维护这么多开源项目, 所以我才制作了这个工具, 只要填一个项目名称, 就自动生成所有需要的脚本. 你有什么点子可以跟我分享, 我们可以一起做, 把你加到 author 里.

**Comment by lndyzwdxhs** [comment]
@MacHu-GWU 可以的，以后多多交流 :+1:
